### ISSUE TITLE
New AppApproval: FirebasePushNotifications

### ISSUE THREAD

**Issue by mainLiveBox** [owncloud/app-approval#30]
AppName: FirebasePushNotifications

IssueType: New / This is a first release
StoreURL: n/a
Repo: https://github.com/LiveBoxCloud/nextcloud-firebasepushnotifications.git
Authors: Paolo Manili (paolo.manili@liveboxcloud.com) , Filippo Martini (filippo.martini@liveboxcloud.com)
Comments: This app was developed following the Owncloud App development manual and some help from the Activity app codebase (for file event hooks handling and examples in service registration). This app allowes compliant Android and iOS owncloud clients to register for Firebase notifications (related to FS events). The app also allows fine grained control over which notifications admins and users want to send. 

We look forward to suggestions and feedback as it is the first OwnCloud app we write and release.

**Comment by JKawohl** [comment]
@DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment]
Since this is the first release - we need a bit more time to review - I'll com back to you next week after my vacation.

**Comment by DeepDiver1975** [comment]
from a pure development point of view: any kind of continuous integration and unit testing is missing. 

in order to get this app uploaded to marketplace.owncloud.com - which replaces the old appstore - you might find things missing:
- appinfo/info.xml
  - no owncloud version dependency
  - no category
  - no screenshot (please use a neutral or owncloud related screenshot)
  - summary missing
  -  AGPL
- the settings classes will not work in owncloud - the interfaces between owncloud and next cloud differ 

Please test your app in owncloud as well - not only in nextcloud
